### ISSUE TITLE
HWDB: Trie search not working correctly

### ISSUE THREAD

**Issue by tuna-f1sh** [cr8t/udev#25]
Seems like I didn't test fully #23 as it still doesn't seem to work properly. It often incorrectly returns:

## Too many keys

```
❯ cargo run --example systemd-hwdb "usb:v1D6Bp0001"
ID_USB_CLASS_FROM_DATABASE: Audio
ID_USB_SUBCLASS_FROM_DATABASE: Boot Interface Subclass
ID_USB_SUBCLASS_FROM_DATABASE: MCTCP Host
# ^ above are not valid returns
ID_VENDOR_FROM_DATABASE: Linux Foundation
ID_AUTOSUSPEND: 1
ID_MODEL_FROM_DATABASE: 1.1 root hub
```

```
❯ systemd-hwdb query usb:v1D6Bp0001                                                                                                                                                          
ID_VENDOR_FROM_DATABASE=Linux Foundation                                                                                                                                                     
ID_AUTOSUSPEND=1                                                                                                                                                                             
ID_MODEL_FROM_DATABASE=1.1 root hub 
```

# No results

```
❯ cargo run --example systemd-hwdb "usb:v*p*d*dc03*"
```

```
❯ systemd-hwdb query "usb:v*p*d*dc03*"
ID_USB_CLASS_FROM_DATABASE=Human Interface Device
```

This isn't critical for me but wanted to capture the issue. I know hwdb isn't well documented so it's hard to dig into this bug. Since it almost there though wondered if you have any ideas. I have updated the test and the example above is in my fork: https://github.com/cr8t/udev/compare/main...tuna-f1sh:udev:main

**Comment by cr8t** [comment]
> I know hwdb isn't well documented so it's hard to dig into this bug.

This is a big pain point for me. The only documentation is very high-level, and it seems the "implementation is the specification". The C code (both systemd udev and eudev) is not the easiest to read, even for someone familiar with C.

> Since it almost there though wondered if you have any ideas.

I have none so far, since I haven't had a chance to look at it yet. I'll dig into it more, and see if I can find a fix.

> I have updated the test and the example above is in my fork: https://github.com/cr8t/udev/compare/main...tuna-f1sh:udev:main

Thank you for providing such detailed bug reports, and continuing to follow-up on this problem. I'll use your fork as a starting point, and go from there.

**Comment by tuna-f1sh** [comment]
Thanks. I got a bit of time at the start of the week to explore this a bit. No revelations unfortunately. 

Mainly spent time walking through function chain for a search comparing with https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-hwdb/sd-hwdb.c . I understand how you've ported from C to Rust and it all appears valid to me - the memory offsets at least, which is confirmed by the fact the trie_strings printed are valid.

I think were this is going wrong is the traversal of the trie. It seems to be continuing to match at the wrong depth - the `ID_USB_SUBCLASS` keys for "usb:v1D6Bp0001" for example. And then not the class for this wildcard ""usb:v*p*d*dc03*". Could not find the culprit though.
